[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/mijnhost/certbot-dns-mijn-host"
Issues = "https://github.com/mijnhost/certbot-dns-mijn-host/issues"
